### ISSUE TITLE
Error Installing ROS2 Foxy diagnostics-updater from apt

### ISSUE THREAD

**Issue by Michael-Equi** [ros/diagnostics#151] opened 2020-07-10 21:04 UTC
I am on Ubuntu 20.04 running ROS2 Foxy and I attempted to install diagnostics_updater from apt using the following command:

`sudo apt-get install ros-foxy-diagnostic-updater`

I received the following error which makes it look like the package was not deployed properly as it is indeed missing at the address that apt tried to get the package from.

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  ros-foxy-diagnostic-updater
0 upgraded, 1 newly installed, 0 to remove and 100 not upgraded.
Need to get 81.2 kB of archives.
After this operation, 368 kB of additional disk space will be used.
Err:1 http://packages.ros.org/ros2/ubuntu focal/main amd64 ros-foxy-diagnostic-updater amd64 2.0.2-1focal.20200624.181109
  404  Not Found [IP: 140.211.166.134 80]
E: Failed to fetch http://packages.ros.org/ros2/ubuntu/pool/main/r/ros-foxy-diagnostic-updater/ros-foxy-diagnostic-updater_2.0.2-1focal.20200624.181109_amd64.deb  404  Not Found [IP: 140.211.166.134 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

**Comment by Karsten1987** [comment] 2020-07-20 22:00
I couldn't reproduce this behavior locally. I've tried it with the official [foxy dockerfile](https://discourse.ros.org/t/announcing-ros-foxy-docker-images-availability/14511) and the updater was installing just fine.

From your output, I suspect there's some misconfiguration locally happening on your machine. Have you tried calling `apt-get update`?

I am going to close this ticket. Please don't hesitate to re-open it the moment you can provide a few more insights or a reproducible example such as a Dockerfile or similar.

**Closed as completed by Karsten1987** 2020-07-20 22:00 UTC
Labels: ros2
